baseURL = 'https://ranmoanran.github.io/moran-blog/'
title = '笔墨文思'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh'
timeZone = 'Asia/Shanghai'

theme = 'ink-thought'
enableRobotsTXT = true

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[security]
  [security.http]
    methods = ['GET']
    urls = [
      'https://plink.anyfeeder.com/.*',
      'https://www.huxiu.com/.*'
    ]

[outputFormats]
  [outputFormats.RSS]
    baseName = 'atom'

[taxonomies]
  tag = 'tags'
  category = 'categories'

[permalinks]
  posts = '/posts/:slug/'

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    lineNos = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false

[related]
  threshold = 80
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = 'tags'
    weight = 120

  [[related.indices]]
    name = 'categories'
    weight = 100

  [[related.indices]]
    name = 'keywords'
    weight = 80

  [[related.indices]]
    name = 'date'
    weight = 10

[pagination]
  pagerSize = 10

[params]
  description = '记录代码与生活的间隙'
  slogan = '记录代码与生活的间隙'
  accent = '#0B3D91'
  homeLatestCount = 6
  socialImage = ''
  socialImageAlt = ''

  [params.profile]
    name = '墨然'
    bio = '程序猿一枚，喜欢瞎捣鼓 . never stand still'
    location = 'Asia/Shanghai'

  [[params.social]]
    name = 'GitHub'
    url = 'https://github.com/RanMoAnRan'
    icon = 'github'

  [[params.social]]
    name = 'Email'
    url = 'mailto:ranmoanran@qq.com'
    icon = 'email'

  [params.post]
    license = '本文采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议。'

  [params.giscus]
    enabled = true
    repo = 'RanMoAnRan/giscus-blog'
    repoId = 'R_kgDOQ9Wupg'
    category = 'Announcements'
    categoryId = 'DIC_kwDOQ9Wups4C1LrJ'
    mapping = 'pathname'
    reactionsEnabled = '1'
    emitMetadata = '0'
    inputPosition = 'top'
    theme = 'light'
    lang = 'zh-CN'
    crossorigin = "anonymous"

  [params.analytics]
    umamiWebsiteId = ''
    umamiSrc = ''
    googleAnalyticsId = ''

[menu]
  [[menu.main]]
    name = '首页'
    pageRef = '/'
    weight = 10

  [[menu.main]]
    name = '归档'
    pageRef = '/archives/'
    weight = 20

  [[menu.main]]
    name = '标签'
    pageRef = '/tags/'
    weight = 30

  [[menu.main]]
    name = '分类'
    pageRef = '/categories/'
    weight = 40

  [[menu.main]]
    name = '订阅'
    pageRef = '/subscribe/'
    weight = 45

  [[menu.main]]
    name = '关于'
    pageRef = '/about/'
    weight = 50
